#!/bin/bash
# Update README examples before committing.

# Skip hook during rebase.
if [ -n "$(git branch | grep "no branch")" ] || [ -n "$GIT_REFLOG_ACTION" ]; then
    echo "Rebase detected: skipping pre-commit hook" >&2
    exit 0
fi

set -euo pipefail

INPUT_PATH=README.md.in
OUTPUT_PATH=README.md

# Use staged version of file to exclude uncommitted changes.
input=$(git show :"$INPUT_PATH")

# Replace lines "!path/to/file" with the contents of the file.
while IFS= read -r line; do
    if [[ $line != !* ]]; then
        echo "$line"
        continue
    fi

    path="${line#!}"
    if [[ ! -f "$path" ]]; then
        echo "ERROR: Failed to find \"$path\"" >&2
        exit 1
    fi

	git show :"$path"
done <<< $input > $OUTPUT_PATH

git add $OUTPUT_PATH
