#!/bin/bash
# Update example in README before committing.

set -euo pipefail

INPUT_PATH=README.md.in
OUTPUT_PATH=README.md

input=$(git show :"$INPUT_PATH")

# Replace lines "!path/to/file" with the contents of the file.
while IFS= read -r line; do
    if [[ $line != !* ]]; then
        echo "$line"
        continue
    fi

    path="${line#!}"
    if [[ ! -f "$path" ]]; then
        echo "ERROR: Failed to find \"$path\"" >&2
        exit 1
    fi

    # Use staged version of file to exclude uncommitted changes.
	git show :"$path"
done <<< $input > $OUTPUT_PATH

git add $OUTPUT_PATH
